### ISSUE TITLE
这个是为vite提供cjs的支持吗

### ISSUE THREAD

**Issue by xiaosenzhang** [xiaoxiangmoe/vite-plugin-commonjs-externals#1]
创建了一个vite react 模板，是我用的不对吗
![image](https://user-images.githubusercontent.com/31362628/109947402-3cee4c00-7d14-11eb-8592-6b0d03ce152a.png)
![image](https://user-images.githubusercontent.com/31362628/109947542-64451900-7d14-11eb-8f33-600b582d3f9e.png)
![image](https://user-images.githubusercontent.com/31362628/109947577-6e671780-7d14-11eb-8e6a-09fb419e6be1.png)

**Comment by xiaoxiangmoe** [comment]
这个项目主要是给 vite 提供 electron 支持的，因为 electron 在很多情况下只支持 cjs。

如果你只是开发普通前端项目，想用 cjs 的库，vite 默认就支持。

**Comment by xiaosenzhang** [comment]
> 这个项目主要是给 vite 提供 electron 支持的，因为 electron 在很多情况下只支持 cjs。
> 
> 如果你只是开发普通前端项目，想用 cjs 的库，vite 默认就支持。

vite支持好像不太友好，我引入的第三方插件（react-intl-universal）中用了global；以及其它的插件中用到的require，支持都不太友好

**Comment by xiaoxiangmoe** [comment]
这个应该去 vite 下提 bug。这个项目，目前的主要目的是提供 electron 支持。
