### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by sfjohnson** [xiaoxiangmoe/vite-plugin-commonjs-externals#16]
Hello!

I was able to get this plugin working with Svelte by changing one line of code. Would it be possible to merge this and publish it as v0.1.4 on npm?

Here is the PR: https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals/pull/15

Thank you.

**Comment by sfjohnson** [comment]
Hello again,

Thank you for merging my PR. Would it be possible to publish this change on NPM as well? That way I can delete my fork.

**Comment by xiaoxiangmoe** [comment]
okay， let me publish it

**Comment by xiaoxiangmoe** [comment]
see https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals/commit/dbf62259bd578d8db3a19c6af4ec2f95cff0ea2a
