### ISSUE TITLE
commonjsExternals is not a function

### ISSUE THREAD

**Issue by chengOnLine** [xiaoxiangmoe/vite-plugin-commonjs-externals#9]
commonjsExternals is not a function

import commonjsExternals from 'vite-plugin-commonjs-externals';
export default defineConfig({
  plugins: [
    vue(),
    commonjsExternals({ externals: ['crypto' , 'buffer' , 'fs'] }),

  ],
})

**Comment by TalexDreamSoul** [comment]
I meet this problem either.
So how to solve it ??

**Comment by yaojiadong666** [comment]
> 
import commonjsExternals from 'vite-plugin-commonjs-externals';
 
export default defineConfig({
   plugins: [
       vue(),
       commonjsExternals?.default({ externals: ['crypto' , 'buffer' , 'fs'] }),
 
   ],
})


> commonjsExternals is not a function
> 
> import commonjsExternals from 'vite-plugin-commonjs-externals'; export default defineConfig({ plugins: [ vue(), commonjsExternals({ externals: ['crypto' , 'buffer' , 'fs'] }),
> 
> ], })

> 

**### solution**
import commonjsExternals from 'vite-plugin-commonjs-externals';
 
export default defineConfig({
   plugins: [
       vue(),
       commonjsExternals?.default({ externals: ['crypto' , 'buffer' , 'fs'] }),
 
   ],
})

**Comment by xiaoxiangmoe** [comment]
@yaojiadong666 Thank you .I known what it happened！

I'll fix it today.

**Comment by xiaoxiangmoe** [comment]
@yaojiadong666 @chengOnLine @TalexDreamSoul What's your node and vite version?

**Comment by yaojiadong666** [comment]
> @yaojiadong666 @chengOnLine @TalexDreamSoul What's your node and vite version?

Node v14.19.0  Vite 4.2.0

**Comment by xiaoxiangmoe** [comment]
I can't reproduce problem in my laptop.

But maybe I can simplify esm and cjs output.

------

Can you try this branch?
yarn install && yarn pack

https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals/tree/update-build

If this fix you problem, i'll publish it.

**Comment by TalexDreamSoul** [comment]
> > @yaojiadong666 @chengOnLine @TalexDreamSoul What's your node and vite version?
> 
> Node v14.19.0  Vite 4.2.0

It's same to me.

**Comment by xiaoxiangmoe** [comment]
@TalexDreamSoul Can you try this branch?
https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals/tree/update-build

**Comment by xiaoxiangmoe** [comment]
@TalexDreamSoul @yaojiadong666 

I can't reproduce problem in my laptop, So I don't know weather my branch is fixing it.

Or can you provide me a minimal reproduction?

**Comment by iperez-bsale** [comment]
I'm getting the exact same error using electron-vite 1.0.21, Node v18.16.0 and vite 4.2.1, I'm also using Typescript 4.9.5

**Comment by IsraPerez98** [comment]
I'm getting the exact same error using electron-vite 1.0.21, Node v18.16.0 and vite 4.2.1, I'm also using Typescript 4.9.5

**Comment by xiaoxiangmoe** [comment]
@IsraPerez98 Can you provide me a minimal reproduction?

**Comment by IsraPerez98** [comment]
I built a repo containing this issue using @quick-start/electron.

[IsraPerez98/commonjsexternals-issue-minimal-reproduction](https://github.com/IsraPerez98/commonjsexternals-issue-minimal-reproduction).

The plugin is used in [electron.vite.config.ts](https://github.com/IsraPerez98/commonjsexternals-issue-minimal-reproduction/blob/main/electron.vite.config.ts).

I forgot if i had to use this plugin on main, preload or renderer, but any of those will fail with the same error.

**Comment by TalexDreamSoul** [comment]
> I can't reproduce problem in my laptop.
> 
> But maybe I can simplify esm and cjs output.
> 
> Can you try this branch? yarn install && yarn pack
> 
> [`update-build`](https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals/tree/update-build?rgh-link-date=2023-05-17T05%3A28%3A15Z)
> 
> If this fix you problem, i'll publish it.

How could I use this branch simply??

**Comment by TalexDreamSoul** [comment]
I just want to use the `update-build` branch in my project, but don't know where to start.
Maybe I should fetch it and build it??

**Comment by TalexDreamSoul** [comment]
I fetch the repository and build it.
The new version seems to work.

![image](https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals/assets/59305952/90fca706-29dd-42c7-971b-28df65a39a77)

It's a simple screenshot about it.

`It worked!!`

**Comment by TalexDreamSoul** [comment]
Hope you could release the  new version as soon as possible, it is important for me. Thanks!

**Comment by xiaoxiangmoe** [comment]
Hi, all, see [0.1.3](https://www.npmjs.com/package/vite-plugin-commonjs-externals/v/0.1.3)
